version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: events-postgres
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: events_user
      POSTGRES_PASSWORD: events_pass
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  events-app:
    build: .
    container_name: events-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/events
      SPRING_DATASOURCE_USERNAME: events_user
      SPRING_DATASOURCE_PASSWORD: events_pass
      TZ: Asia/Kolkata
    ports:
      - "8080:8080"

volumes:
  pg_data:
